[package]
name = "main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base" }
files = { path = "../files" }
movies = { path = "../movies" }

rocket = "0.5.0-rc"
